apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-data
  namespace: csf-platform
spec:
  accessModes:
    - ReadWriteMany        # Azure Files — allows CronJob + dashboard to mount simultaneously
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
